## Set up Taxa data and Mapping data
## Ryan Blaustein <ryan.blaustein@northwestern.edu>
## 12-18-2019

### set wd to */Toothbrush_Microbiome_Project

##########
########## PREP METAPHLAN DATA FOR SOURCETRACKER: SPECIES ##########
##########

#####
##### Prep taxa tables
#####

## read in species-level taxa tables generated by metaphlan for (i) toothbrush study, (ii) oregon dataset (Fahimipour et al. 2018) (iii) gerlinger dataset 
## (Hartmann et al. 2016), and (iv) HMP (manually edited from hmp1-II_metaphlan2-mtd-qcd.txt downloaded from <https://www.hmpdacc.org/hmp/hmsmcp2/>)
toothbrush.species.meta <- read.table('data/taxa_tables/species/toothbrush_metaphlan_species.txt',
                                      header = T, sep = '\t', row.names = 1, skip = 1, comment.char = '')

oreg.species.meta <- read.table('data/taxa_tables/species/oreg_metaphlan_species.txt',
                                header = T, sep = '\t', row.names = 1, skip = 1, comment.char = '')

gerl.species.meta <- read.table('data/taxa_tables/species/gerl_metaphlan_species.txt',
                                header = T, sep = '\t', row.names = 1, skip = 1, comment.char = '')

hmp.species.meta <- read.table('data/taxa_tables/species/hmp_metaphlan_species.txt',
                               header = T, sep = '\t', row.names = 1, skip = 1, comment.char = '')

## set all taxa tables to have proportional abundances (if not already)
apply(toothbrush.species.meta,2,sum)
toothbrush.species.meta = toothbrush.species.meta/100

apply(oreg.species.meta,2,sum)
oreg.species.meta = oreg.species.meta/100

apply(gerl.species.meta,2,sum)
gerl.species.meta = gerl.species.meta/100

apply(hmp.species.meta,2,sum)

# check average values -- should be 0.9-1.0
c(mean(apply(toothbrush.species.meta,2,sum)),
  mean(apply(oreg.species.meta,2,sum)),
  mean(apply(gerl.species.meta,2,sum)),
  mean(apply(hmp.species.meta,2,sum)))

## merge taxa data for toothbrush and hmp by common rownames
taxa_merge_tb_hmp <- merge.data.frame(toothbrush.species.meta, 
                                      hmp.species.meta,
                                      by=0, all=TRUE)
rownames(taxa_merge_tb_hmp) = taxa_merge_tb_hmp[,1]
taxa_merge_tb_hmp = taxa_merge_tb_hmp[,-c(1)]
taxa_merge_tb_hmp[is.na(taxa_merge_tb_hmp)] <- 0

## update merge taxa with oregon dataset
taxa_merge_tb_hmp_oreg <- merge.data.frame(taxa_merge_tb_hmp, 
                                           oreg.species.meta,
                                           by=0, all=TRUE)
rownames(taxa_merge_tb_hmp_oreg) = taxa_merge_tb_hmp_oreg[,1]
taxa_merge_tb_hmp_oreg = taxa_merge_tb_hmp_oreg[,-c(1)]
taxa_merge_tb_hmp_oreg[is.na(taxa_merge_tb_hmp_oreg)] <- 0

## update merge taxa with gerlinger dataset
taxa_merge_tb_hmp_oreg_gerl <- merge.data.frame(taxa_merge_tb_hmp_oreg, 
                                                gerl.species.meta,
                                                by=0, all=TRUE)
rownames(taxa_merge_tb_hmp_oreg_gerl) = taxa_merge_tb_hmp_oreg_gerl[,1]
taxa_merge_tb_hmp_oreg_gerl = taxa_merge_tb_hmp_oreg_gerl[,-c(1)]
taxa_merge_tb_hmp_oreg_gerl[is.na(taxa_merge_tb_hmp_oreg_gerl)] <- 0

#####
##### Link with metadata/mapping file
#####

## read in map table
mapping_tb_oreg_gerl_hmp <- read.table('data/map_tables/mapping_tb_oreg_gerl_hmp.txt',sep='\t',h=T,row.names=1,check=F,comment='')

## keep only rows that correspond to samples in taxa_merge_oreg_gerl_hmp (i.e., all tb+oregon+hmp samples, 
## and only gerlinger samples that have identical metaphlan barcodes)
mapping_tb_oreg_gerl_hmp_clean <- rbind(mapping_tb_oreg_gerl_hmp[grep("TMP", rownames(mapping_tb_oreg_gerl_hmp)),], 
                                        mapping_tb_oreg_gerl_hmp[grep("SRS", rownames(mapping_tb_oreg_gerl_hmp)),],
                                        mapping_tb_oreg_gerl_hmp[grep("AF", rownames(mapping_tb_oreg_gerl_hmp)),],
                                         mapping_tb_oreg_gerl_hmp[grep(paste(
                                           intersect(mapping_tb_oreg_gerl_hmp[grep(
                                             mapping_tb_oreg_gerl_hmp$TITLE, pattern = "Gerl"),1:5]$METAPHLAN_BARCODE,
                                             colnames(mapping_tb_oreg_gerl_hmp)),collapse="|"), mapping_tb_oreg_gerl_hmp$METAPHLAN_BARCODE),][order(
                                               mapping_tb_oreg_gerl_hmp[grep(paste(intersect(
                                                 mapping_tb_oreg_gerl_hmp[grep(mapping_tb_oreg_gerl_hmp$TITLE, pattern = "Gerl"),1:5]$METAPHLAN_BARCODE, 
                                                 colnames(taxa_merge_tb_hmp_oreg_gerl)),collapse="|"), mapping_tb_oreg_gerl_hmp$METAPHLAN_BARCODE),
                                                 ]$METAPHLAN_BARCODE),]) 
mapping_tb_oreg_gerl_hmp_clean <- as.data.frame(mapping_tb_oreg_gerl_hmp_clean) 
head(mapping_tb_oreg_gerl_hmp_clean)

## Remove any samples that contain 0 bacterial counts from merge taxa table and mapping table (i.e., AF014, AF101)
# call samples
names(which(apply(taxa_merge_tb_hmp_oreg_gerl, 2, sum) == 0))
# adjust taxa table
taxa_merge_tb_hmp_oreg_gerl_clean <- taxa_merge_tb_hmp_oreg_gerl[,-c(grep("AF014|AF101", colnames(taxa_merge_tb_hmp_oreg_gerl)))]
# adjust mapping table
mapping_tb_oreg_gerl_hmp_clean <- mapping_tb_oreg_gerl_hmp_clean[-c(grep("AF014|AF101", rownames(mapping_tb_oreg_gerl_hmp_clean))),]

## confirm that the order of the taxa table and map table are the same (i.e., compare colnames/rownames for oregon samples,
## colnames/METAPHLAN_BARCODE names for gerlinger samples, and colnames/rownames for hmp samples)
which(as.character(c(paste("TMP", colnames(taxa_merge_tb_hmp_oreg_gerl_clean[,1:34]), sep = "_"),
                     colnames(taxa_merge_tb_hmp_oreg_gerl_clean[,35:2389]), 
                     colnames(taxa_merge_tb_hmp_oreg_gerl_clean[,2390:2509]), 
                     colnames(taxa_merge_tb_hmp_oreg_gerl_clean[,2510:2548])) == c(rownames(mapping_tb_oreg_gerl_hmp_clean[1:34,]), 
                                                                                   rownames(mapping_tb_oreg_gerl_hmp_clean[35:2389,]), 
                                                                                   rownames(mapping_tb_oreg_gerl_hmp_clean[2390:2509,]),
                                                                                   as.character(mapping_tb_oreg_gerl_hmp_clean[2510:2548,]$METAPHLAN_BARCODE)))
      == 'FALSE')

## re-name gerlinger samples: change metaphlan_barcode to sample ID
colnames(taxa_merge_tb_hmp_oreg_gerl_clean) = rownames(mapping_tb_oreg_gerl_hmp_clean)

## confirm consistency in map table and taxa table
which(as.character(colnames(taxa_merge_tb_hmp_oreg_gerl_clean) == rownames(mapping_tb_oreg_gerl_hmp_clean))
      == 'FALSE')

## write taxa table
write.table(taxa_merge_tb_hmp_oreg_gerl_clean, 
            'data/taxa_tables/species/species_merge_tb_hmp_oreg_gerl_clean.txt',sep="\t", 
            col.names=NA, quote = FALSE)

## make taxa table intergral by rounding to a 1000x multiplier**
## **Note: step required to make relative abundance table copatible with SourceTracker
species_merge_tb_hmp_oreg_gerl_1000x <- ceiling(1000*taxa_merge_tb_hmp_oreg_gerl_clean)

## write 1000x taxa table (use in sourcetracker)**
## **Note: manual edit needed to modify first line of table in .txt file for compatibility with SourceTracker
write.table(species_merge_tb_hmp_oreg_gerl_1000x, 
            'data/taxa_tables/species/species_merge_tb_hmp_oreg_gerl_1000x.txt',sep="\t", 
            col.names=NA, quote = FALSE)

## write mapping table
## **Note: manual edit needed to modify first line of table in .txt file for compatibility with SourceTracker
write.table(mapping_tb_oreg_gerl_hmp_clean, 
            'data/map_tables/mapping_tb_oreg_gerl_hmp_clean.txt',sep="\t", 
            col.names=NA, quote = FALSE)


##########
########## PREP METAPHLAN DATA FOR SOURCETRACKER: GENUS ##########
##########

#####
##### Prep taxa tables
#####

## read in genus-level taxa tables generated by metaphlan for (i) toothbrush study, (ii) oregon dataset (Fahimipour et al. 2018) (iii) gerlinger dataset 
## (Hartmann et al. 2016), and (iv) HMP (manually edited from hmp1-II_metaphlan2-mtd-qcd.txt downloaded from <https://www.hmpdacc.org/hmp/hmsmcp2/>)
toothbrush.genus.meta <- read.table('data/taxa_tables/genus/toothbrush_metaphlan_genus.txt',
                                    header = T, sep = '\t', row.names = 1, skip = 1, comment.char = '')

oreg.genus.meta <- read.table('data/taxa_tables/genus/oreg_metaphlan_genus.txt',
                                header = T, sep = '\t', row.names = 1, skip = 1, comment.char = '')

gerl.genus.meta <- read.table('data/taxa_tables/genus/gerl_metaphlan_genus.txt',
                                header = T, sep = '\t', row.names = 1, skip = 1, comment.char = '')

hmp.genus.meta <- read.table('data/taxa_tables/genus/hmp_metaphlan_genus.txt',
                               header = T, sep = '\t', row.names = 1, skip = 1, comment.char = '')

## set all taxa tables to have proportional abundances (if not already)
apply(toothbrush.genus.meta,2,sum)
toothbrush.genus.meta = toothbrush.genus.meta/100

# check average values -- should be 0.9-1.0
c(mean(apply(toothbrush.genus.meta,2,sum)),
  mean(apply(oreg.genus.meta,2,sum)),
  mean(apply(gerl.genus.meta,2,sum)),
  mean(apply(hmp.genus.meta,2,sum)))

## merge taxa data for toothbrush and hmp by common rownames
taxa_merge_tb_hmp <- merge.data.frame(toothbrush.genus.meta, 
                                      hmp.genus.meta,
                                      by=0, all=TRUE)
rownames(taxa_merge_tb_hmp) = taxa_merge_tb_hmp[,1]
taxa_merge_tb_hmp = taxa_merge_tb_hmp[,-c(1)]
taxa_merge_tb_hmp[is.na(taxa_merge_tb_hmp)] <- 0

## update merge taxa with oregon dataset
taxa_merge_tb_hmp_oreg <- merge.data.frame(taxa_merge_tb_hmp, 
                                           oreg.genus.meta,
                                           by=0, all=TRUE)
rownames(taxa_merge_tb_hmp_oreg) = taxa_merge_tb_hmp_oreg[,1]
taxa_merge_tb_hmp_oreg = taxa_merge_tb_hmp_oreg[,-c(1)]
taxa_merge_tb_hmp_oreg[is.na(taxa_merge_tb_hmp_oreg)] <- 0

## update merge taxa with gerlinger dataset
taxa_merge_tb_hmp_oreg_gerl <- merge.data.frame(taxa_merge_tb_hmp_oreg, 
                                                gerl.genus.meta,
                                                by=0, all=TRUE)
rownames(taxa_merge_tb_hmp_oreg_gerl) = taxa_merge_tb_hmp_oreg_gerl[,1]
taxa_merge_tb_hmp_oreg_gerl = taxa_merge_tb_hmp_oreg_gerl[,-c(1)]
taxa_merge_tb_hmp_oreg_gerl[is.na(taxa_merge_tb_hmp_oreg_gerl)] <- 0

#####
##### Link with metadata/mapping file
#####

## read in map table
mapping_tb_oreg_gerl_hmp <- read.table('data/map_tables/mapping_tb_oreg_gerl_hmp.txt',sep='\t',h=T,row.names=1,check=F,comment='')

## keep only rows that correspond to samples in taxa_merge_oreg_gerl_hmp (i.e., all tb+oregon+hmp samples, 
## and only gerlinger samples that have identical metaphlan barcodes)
mapping_tb_oreg_gerl_hmp_clean <- rbind(mapping_tb_oreg_gerl_hmp[grep("TMP", rownames(mapping_tb_oreg_gerl_hmp)),], 
                                        mapping_tb_oreg_gerl_hmp[grep("SRS", rownames(mapping_tb_oreg_gerl_hmp)),],
                                        mapping_tb_oreg_gerl_hmp[grep("AF", rownames(mapping_tb_oreg_gerl_hmp)),],
                                        mapping_tb_oreg_gerl_hmp[grep(paste(
                                          intersect(mapping_tb_oreg_gerl_hmp[grep(
                                            mapping_tb_oreg_gerl_hmp$TITLE, pattern = "Gerl"),1:5]$METAPHLAN_BARCODE,
                                            colnames(mapping_tb_oreg_gerl_hmp)),collapse="|"), mapping_tb_oreg_gerl_hmp$METAPHLAN_BARCODE),][order(
                                              mapping_tb_oreg_gerl_hmp[grep(paste(intersect(
                                                mapping_tb_oreg_gerl_hmp[grep(mapping_tb_oreg_gerl_hmp$TITLE, pattern = "Gerl"),1:5]$METAPHLAN_BARCODE, 
                                                colnames(taxa_merge_tb_hmp_oreg_gerl)),collapse="|"), mapping_tb_oreg_gerl_hmp$METAPHLAN_BARCODE),
                                                ]$METAPHLAN_BARCODE),]) 
mapping_tb_oreg_gerl_hmp_clean <- as.data.frame(mapping_tb_oreg_gerl_hmp_clean) 
head(mapping_tb_oreg_gerl_hmp_clean)

## Remove any samples that contain 0 bacterial counts from merge taxa table and mapping table (i.e., AF014, AF101)
# call samples
names(which(apply(taxa_merge_tb_hmp_oreg_gerl, 2, sum) == 0))
# adjust taxa table
taxa_merge_tb_hmp_oreg_gerl_clean <- taxa_merge_tb_hmp_oreg_gerl[,-c(grep("AF014|AF101", colnames(taxa_merge_tb_hmp_oreg_gerl)))]
# adjuts mapping table
mapping_tb_oreg_gerl_hmp_clean <- mapping_tb_oreg_gerl_hmp_clean[-c(grep("AF014|AF101", rownames(mapping_tb_oreg_gerl_hmp_clean))),]

## confirm that the order of the taxa table and map table are the same (i.e., compare colnames/rownames for oregon samples,
## colnames/METAPHLAN_BARCODE names for gerlinger samples, and colnames/rownames for hmp samples)
which(as.character(c(paste("TMP", colnames(taxa_merge_tb_hmp_oreg_gerl_clean[,1:34]), sep = "_"),
                     colnames(taxa_merge_tb_hmp_oreg_gerl_clean[,35:2389]), 
                     colnames(taxa_merge_tb_hmp_oreg_gerl_clean[,2390:2509]), 
                     colnames(taxa_merge_tb_hmp_oreg_gerl_clean[,2510:2548])) == c(rownames(mapping_tb_oreg_gerl_hmp_clean[1:34,]), 
                                                                                   rownames(mapping_tb_oreg_gerl_hmp_clean[35:2389,]), 
                                                                                   rownames(mapping_tb_oreg_gerl_hmp_clean[2390:2509,]),
                                                                                   as.character(mapping_tb_oreg_gerl_hmp_clean[2510:2548,]$METAPHLAN_BARCODE)))
      == 'FALSE')

## re-name gerlinger samples: change metaphlan_barcode to sample ID
colnames(taxa_merge_tb_hmp_oreg_gerl_clean) = rownames(mapping_tb_oreg_gerl_hmp_clean)

## confirm consistency in map table and taxa table
which(as.character(colnames(taxa_merge_tb_hmp_oreg_gerl_clean) == rownames(mapping_tb_oreg_gerl_hmp_clean))
      == 'FALSE')

## write taxa table
write.table(taxa_merge_tb_hmp_oreg_gerl_clean, 
            'data/taxa_tables/genus/genus_merge_tb_hmp_oreg_gerl_clean.txt',sep="\t", 
            col.names=NA, quote = FALSE)

## make taxa table intergral by rounding to a 1000x multiplier**
## **Note: step required to make relative abundance table copatible with SourceTracker
genus_merge_tb_hmp_oreg_gerl_1000x <- ceiling(1000*taxa_merge_tb_hmp_oreg_gerl_clean)

## write taxa table**
## **Note: manual edit needed to modify first line of table in .txt file for compatibility with SourceTracker
write.table(genus_merge_tb_hmp_oreg_gerl_1000x, 
            'data/taxa_tables/genus/genus_merge_tb_hmp_oreg_gerl_1000x.txt',sep="\t", 
            col.names=NA, quote = FALSE)

## write mapping table
## **Note: manual edit needed to modify first line of table in .txt file for compatibility with SourceTracker
write.table(mapping_tb_oreg_gerl_hmp_clean, 
            'data/map_tables/mapping_tb_oreg_gerl_hmp_clean.txt',sep="\t", 
            col.names=NA, quote = FALSE)
